version: '3'
services:
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: postgres-dev
      POSTGRES_PASSWORD: dev
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - fullstack
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: live@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - db
    links:
      - db
    ports:
      - "5050:80"
    networks:
      - fullstack
    restart: unless-stopped
  app:
    build: .
    container_name: app
    command: ["./wait-for-it.sh", "db:5432", "--", "go", "run", "main.go"]
    volumes:
      - ./src:/go/src/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
    networks:
      - fullstack
networks:
  fullstack:
    driver: bridge