
CREATE SCHEMA APP;

CREATE TABLE APP.USERS(
   USERID       SERIAL PRIMARY KEY,
   USERNAME     VARCHAR (50) UNIQUE NOT NULL,
   EMAIL        VARCHAR (355) UNIQUE NOT NULL,
   FIRSTNAME    VARCHAR (50) NOT NULL,
   LASTNAME     VARCHAR (50) NOT NULL,
   CREATED      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   MODIFATE     TIMESTAMP,
   ACTIVE       BIT(1)
);

CREATE TABLE APP.PASSWORD(
    PASSWORDID      SMALLSERIAL PRIMARY KEY,
    USERID          INTEGER NOT NULL REFERENCES APP.USERS ON DELETE CASCADE ON UPDATE CASCADE,
    PASSWORD        VARCHAR (50) NOT NULL,
    ACTIVE          BIT(1) DEFAULT B'1',
    CREATED         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(USERID) REFERENCES APP.USERS(USERID)
);

CREATE TABLE APP.LOGINATTEMPT(
    LOGINATTEMPTID  SERIAL PRIMARY KEY,
    USERNAME        VARCHAR (50) NOT NULL,
    PASSWORD        VARCHAR (50),
    IPNUMBER        VARCHAR (15),
    BROWSERTYPE     VARCHAR (50),
    SUCCESS         BIT(1) DEFAULT B'0',
    CREATED         TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);